accounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^account/$', views.account_settings, name='account_settings'),
    url(r'^business/settings/$', views.business_settings,
        name='business_settings'),
    url(r'^signout/$', views.auth_logout, name='logout'),
    url(r'^password/change/$', views.password_change, name="password_change"),
    url(r'^password/reset/$', views.password_reset, name="password_reset"),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name="password_reset_confirm"),
]

api/urls.py
from django.conf.urls import url

from push_notifications.api.views import APNSDeviceAuthorizedViewSet

from . import views
from .views import APIHomeView, TimelineAPIView
from .views import (AccountCreateAPIView,
                    MyUserDetailAPIView, MyUserListAPIView)
from .views import CommentCreateAPIView, CommentDetailAPIView
from .views import HashtagPhotoListAPIView, HashtagTrendingListAPIView
from .views import (CategoryDetailAPIView, CategoryListAPIView,
                    PhotoListAPIView, PhotoCreateAPIView, PhotoDetailAPIView)
from .views import NotificationAPIView, NotificationAjaxAPIView
from .views import (PasswordChangeView, PasswordResetView,
                    PasswordResetConfirmView)
from .views import (ProductCreateAPIView, ProductDetailAPIView,
                    ProductListAPIView, ProductRedeemedListAPIView)
from .views import SearchListAPIView


urlpatterns = [
    # G E N E R A L
    url(r'^$', APIHomeView.as_view(),
        name='api_home'),
    url(r'^homepage/$', views.homepage_api_view,
        name='homepage_api'),
    url(r'^timeline/$', TimelineAPIView.as_view(),
        name='timeline_api'),
    url(r'^search/$', SearchListAPIView.as_view(),
        name='search_api'),
    url(r'^device/apns/$',
        APNSDeviceAuthorizedViewSet.as_view({'post': 'create'}),
        name='create_apns_device'),

    # A C C O U N T S
    url(r'^accounts/$', MyUserListAPIView.as_view(),
        name='user_account_list_api'),
    url(r'^accounts/create/$', AccountCreateAPIView.as_view(),
        name='account_create_api'),
    url(r'^accounts/(?P<username>[\w.@+-]+)/$', MyUserDetailAPIView.as_view(),
        name='user_account_detail_api'),
    url(r'^support/(?P<user_pk>\d+)/$', views.follow_create_api,
        name='follow_create_api'),
    url(r'^block/(?P<user_pk>\d+)/$', views.block_user_api,
        name='block_user_api'),

    # A U T H E N T I C A T I O N
    url(r'^password/reset/$', PasswordResetView.as_view(),
        name='rest_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='rest_password_reset_confirm'),
    url(r'^password/change/$', PasswordChangeView.as_view(),
        name='rest_password_change'),

    # C O M M E N T S
    url(r'^comments/create/$', CommentCreateAPIView.as_view(),
        name='comment_create_api'),
    url(r'^comments/(?P<id>\d+)/$', CommentDetailAPIView.as_view(),
        name='comment_detail_api'),

    # F L A G S
    url(r'^flag/create/(?P<photo_pk>\d+)/$', views.flag_create_api,
        name='flag_create_api'),

    # H A S H T A G S
    url(r'^hashtags/$', HashtagPhotoListAPIView.as_view(),
        name='hashtag_photo_list_api'),
    url(r'^hashtags/trending/$', HashtagTrendingListAPIView.as_view(),
        name='hashtag_trending_list_api'),

    # N O T I F I C A T I O N S
    url(r'^notifications/$', NotificationAPIView.as_view(),
        name='notification_list_api'),
    url(r'^notifications/unread/$', NotificationAjaxAPIView.as_view(),
        name='get_unread_notifications_api'),

    # P H O T O S
    url(r'^categories/$', CategoryListAPIView.as_view(),
        name='category_list_api'),
    url(r'^categories/(?P<slug>[\w-]+)/$', CategoryDetailAPIView.as_view(),
        name='category_detail_api'),
    url(r'^photos/$', PhotoListAPIView.as_view(),
        name='photo_list_api'),
    url(r'^photos/create/$', PhotoCreateAPIView.as_view({'post': 'create'}),
        name='photo_create_api'),
    url(r'^photos/(?P<cat_slug>[\w-]+)/(?P<photo_slug>[\w-]+)/$',
        PhotoDetailAPIView.as_view(),
        name='photo_detail_api'),
    url(r'^like/(?P<photo_pk>\d+)/$', views.like_create_api,
        name='like_create_api'),

    # S H O P
    url(r'^shop/$', ProductListAPIView.as_view(),
        name='product_list_api'),
    url(r'^shop/redeemed/$', ProductRedeemedListAPIView.as_view(),
        name='product_redeemed_api'),
    url(r'^shop/create/$', ProductCreateAPIView.as_view({'post': 'create'}),
        name='product_create_api'),
    url(r'^shop/product/(?P<product_slug>[\w-]+)/$',
        ProductDetailAPIView.as_view(),
        name='product_detail_api'),
    url(r'^shop/rewards/check/$', views.reward_check_view,
        name='reward_check_view'),
    url(r'^shop/rewards/redeemed/$', views.reward_redeemed_view,
        name='reward_redeemed_view'),
    url(r'^shop/rewards/purchase/(?P<product_pk>\d+)/$',
        views.reward_purchase_view,
        name='reward_purchase_view'),
]

contact/urls.py
from django.conf.urls import url

from . import views


app_name = 'contact'
urlpatterns = [
    url(r'^business/inquiry/$', views.business_inquiry,
        name='business_inquiry'),
    url(r'^business/signup/$', views.business_signup,
        name='business_signup'),
]

templates/visitor/home_visitor.html
{% extends "simple_base.html" %}
{% load staticfiles %}

{% block title %}OBY{% endblock title %}

{% block js %}
    <script src="{% static 'js/jquery-color.min.js' %}" type="text/javascript" defer></script>
    <script src="{% static 'js/bg-change.min.js' %}" type="text/javascript" defer></script>
{% endblock js %}

{% block content %}
    <div class="visitor-container">
        <div class="col-md-12 slide section">
            <img src="{% static 'img/oby_transparent.png' %}" class="home-logo" />
            <h1 class="home-motto">CREATE. SHARE. THRIVE.</h1>
            <div class="col-md-12 home-caret">
                <img src="{% static 'img/caret.png' %}" class="jumper" locator="#findme"/>
            </div>
        </div>
        <div class="col-md-12 slide section" id="findme">
            <div class="col-md-4">
                <img src="{% static 'img/detail-one.png' %}" />
                <h3 class="detail-description">
                    Craft a memory.<br/>
                    Inspire others.
                </h3>
            </div>
            <div class="col-md-4">
                <img src="{% static 'img/detail-two.png' %}" />
                <h3 class="detail-description">
                    Share your creations.<br/>
                    Like, comment, and discover.
                </h3>
            </div>
            <div class="col-md-4">
                <img src="{% static 'img/detail-three.png' %}" />
                <h3 class="detail-description">
                    Thrive by putting<br/>
                    others before yourself.
                </h3>
            </div>
        </div>
        <div class="col-md-12 slide">
            <div class="col-md-12 app-store-badge">
                <a href="https://itunes.apple.com/us/app/oby/id1070867159?mt=8">
                    <img src="{% static 'img/app_store_135x40.svg' %}" />
                </a>
            </div>
            <div class="col-md-12">
                <h3>
                    <a href="{% url 'login' %}" class="submit-btn home-submit-btn signin-btn">Sign in</a>
                    <a href="{% url 'register' %}" class="submit-btn home-submit-btn special-btn">Sign up</a>
                </h3>
            </div>
        </div>
        <div class="col-sm-12 visitor-footer">
            <a href="{% url 'about' %}" class="visitor-footer-item">About</a>
            <a href="{% url 'contact:business_inquiry' %}" class="visitor-footer-item">Partnerships</a>
            <a href="mailto:team@obystudio.com" class="visitor-footer-item">team@obystudio.com</a>
            <a href="{% url 'privacy_policy' %}" class="visitor-footer-item">Privacy</a>
            <a href="{% url 'terms_of_use' %}" class="visitor-footer-item">Terms</a>
            <p class="visitor-footer-item">&copy; 2016 OBY</p>
        </div>
    </div>
{% endblock content %}

templates/visitor/login_register.html
{% extends "simple_base.html" %}
{% load crispy_forms_tags %}

{% block title %}OBY / Authenticate{% endblock title %}

<style>
    {% block style %}
        body{
            background: #F9615B; /* For browsers that do not support gradients */
            background: -webkit-linear-gradient(#87080c, #b44d3e); /* For Safari 5.1 to 6.0 */
            background: -o-linear-gradient(#87080c, #b44d3e); /* For Opera 11.1 to 12.0 */
            background: -moz-linear-gradient(#87080c, #b44d3e); /* For Firefox 3.6 to 15 */
            background: linear-gradient(#87080c, #b44d3e); /* Standard syntax */
        }
    {% endblock style %}
</style>

{% block content %}
    <div class="authentication-container">
        <div class="col-sm-12">
            <h1>{{ title }}</h1>
            <br/>
        </div>
        <div class="col-sm-4 col-sm-offset-4">
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}
                {{ form|crispy }}
                <br/>
                <input type="hidden" name="next" value="/" />
                <input class="submit-btn signin-btn btn-block" type="submit" value="{{ submit_btn }}" />
            </form>
            {% if title == "Register" %}
                    <p class="account-create-agreement">
                        Creating an account means you're okay with OBY's<br/>
                        <a href="{% url 'terms_of_use' %}">Terms</a> and <a href="{% url 'privacy_policy' %}">Privacy</a> policies.
                    </p>
                {% endif %}
			<br/>
            <div class="redirect-link">
                {% if title == "Sign in" %}
                    <br/>
                    <p>Don't have an account? <a href="{% url 'register' %}">Sign up now!</a></p>
                    <a href="{% url 'accounts:password_reset' %}" class="forgot-password">Forgot your password?</a>
                {% endif %}

                {% if title == "Register" %}
                    <br/>
                    <p>Already have an account? <a href="{% url 'login' %}">Sign in!</a></p>
                {% endif %}
            </div>
        </div>
        <div class="col-sm-12 visitor-footer" style="text-shadow: none;">
            <a href="{% url 'home' %}" class="visitor-footer-item">OBY</a>
            <a href="{% url 'about' %}" class="visitor-footer-item">About</a>
            <a href="mailto:team@obystudio.com" class="visitor-footer-item">team@obystudio.com</a>
            <a href="{% url 'privacy_policy' %}" class="visitor-footer-item">Privacy</a>
            <a href="{% url 'terms_of_use' %}" class="visitor-footer-item">Terms</a>
            {% if title == "Sign in" %}
                <a href="{% url 'register' %}" class="visitor-footer-item">Sign up</a>
            {% endif %}
            {% if title == "Register" %}
                <a href="{% url 'login' %}" class="visitor-footer-item">Sign in</a>
            {% endif %}
            <p class="visitor-footer-item">&copy; 2016 OBY</p>
        </div>
    </div>
{% endblock content %}