accounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^account/$', views.account_settings, name='account_settings'),
    url(r'^business/settings/$', views.business_settings,
        name='business_settings'),
    url(r'^signout/$', views.auth_logout, name='logout'),
    url(r'^password/change/$', views.password_change, name="password_change"),
    url(r'^password/reset/$', views.password_reset, name="password_reset"),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name="password_reset_confirm"),
]

api/urls.py
from django.conf.urls import url

from push_notifications.api.views import APNSDeviceAuthorizedViewSet

from . import views
from .views import APIHomeView, TimelineAPIView
from .views import (AccountCreateAPIView,
                    MyUserDetailAPIView, MyUserListAPIView)
from .views import CommentCreateAPIView, CommentDetailAPIView
from .views import HashtagPhotoListAPIView, HashtagTrendingListAPIView
from .views import (CategoryDetailAPIView, CategoryListAPIView,
                    PhotoListAPIView, PhotoCreateAPIView, PhotoDetailAPIView)
from .views import NotificationAPIView, NotificationAjaxAPIView
from .views import (PasswordChangeView, PasswordResetView,
                    PasswordResetConfirmView)
from .views import (ProductCreateAPIView, ProductDetailAPIView,
                    ProductListAPIView, ProductRedeemedListAPIView)
from .views import SearchListAPIView


urlpatterns = [
    # G E N E R A L
    url(r'^$', APIHomeView.as_view(),
        name='api_home'),
    url(r'^homepage/$', views.homepage_api_view,
        name='homepage_api'),
    url(r'^timeline/$', TimelineAPIView.as_view(),
        name='timeline_api'),
    url(r'^search/$', SearchListAPIView.as_view(),
        name='search_api'),
    url(r'^device/apns/$',
        APNSDeviceAuthorizedViewSet.as_view({'post': 'create'}),
        name='create_apns_device'),

    # A C C O U N T S
    url(r'^accounts/$', MyUserListAPIView.as_view(),
        name='user_account_list_api'),
    url(r'^accounts/create/$', AccountCreateAPIView.as_view(),
        name='account_create_api'),
    url(r'^accounts/(?P<username>[\w.@+-]+)/$', MyUserDetailAPIView.as_view(),
        name='user_account_detail_api'),
    url(r'^support/(?P<user_pk>\d+)/$', views.follow_create_api,
        name='follow_create_api'),
    url(r'^block/(?P<user_pk>\d+)/$', views.block_user_api,
        name='block_user_api'),

    # A U T H E N T I C A T I O N
    url(r'^password/reset/$', PasswordResetView.as_view(),
        name='rest_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='rest_password_reset_confirm'),
    url(r'^password/change/$', PasswordChangeView.as_view(),
        name='rest_password_change'),

    # C O M M E N T S
    url(r'^comments/create/$', CommentCreateAPIView.as_view(),
        name='comment_create_api'),
    url(r'^comments/(?P<id>\d+)/$', CommentDetailAPIView.as_view(),
        name='comment_detail_api'),

    # F L A G S
    url(r'^flag/create/(?P<photo_pk>\d+)/$', views.flag_create_api,
        name='flag_create_api'),

    # H A S H T A G S
    url(r'^hashtags/$', HashtagPhotoListAPIView.as_view(),
        name='hashtag_photo_list_api'),
    url(r'^hashtags/trending/$', HashtagTrendingListAPIView.as_view(),
        name='hashtag_trending_list_api'),

    # N O T I F I C A T I O N S
    url(r'^notifications/$', NotificationAPIView.as_view(),
        name='notification_list_api'),
    url(r'^notifications/unread/$', NotificationAjaxAPIView.as_view(),
        name='get_unread_notifications_api'),

    # P H O T O S
    url(r'^categories/$', CategoryListAPIView.as_view(),
        name='category_list_api'),
    url(r'^categories/(?P<slug>[\w-]+)/$', CategoryDetailAPIView.as_view(),
        name='category_detail_api'),
    url(r'^photos/$', PhotoListAPIView.as_view(),
        name='photo_list_api'),
    url(r'^photos/create/$', PhotoCreateAPIView.as_view({'post': 'create'}),
        name='photo_create_api'),
    url(r'^photos/(?P<cat_slug>[\w-]+)/(?P<photo_slug>[\w-]+)/$',
        PhotoDetailAPIView.as_view(),
        name='photo_detail_api'),
    url(r'^like/(?P<photo_pk>\d+)/$', views.like_create_api,
        name='like_create_api'),

    # S H O P
    url(r'^shop/$', ProductListAPIView.as_view(),
        name='product_list_api'),
    url(r'^shop/redeemed/$', ProductRedeemedListAPIView.as_view(),
        name='product_redeemed_api'),
    url(r'^shop/create/$', ProductCreateAPIView.as_view({'post': 'create'}),
        name='product_create_api'),
    url(r'^shop/product/(?P<product_slug>[\w-]+)/$',
        ProductDetailAPIView.as_view(),
        name='product_detail_api'),
    url(r'^shop/rewards/check/$', views.reward_check_view,
        name='reward_check_view'),
    url(r'^shop/rewards/redeemed/$', views.reward_redeemed_view,
        name='reward_redeemed_view'),
    url(r'^shop/rewards/purchase/(?P<product_pk>\d+)/$',
        views.reward_purchase_view,
        name='reward_purchase_view'),
]

contact/urls.py
from django.conf.urls import url

from . import views


app_name = 'contact'
urlpatterns = [
    url(r'^business/inquiry/$', views.business_inquiry,
        name='business_inquiry'),
    url(r'^business/signup/$', views.business_signup,
        name='business_signup'),
]

templates/advertisers/advertiser_view.html
{% extends "simple_base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ user }}{% endblock title %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/jquery.lazyload.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            $("img.lazy").lazyload({threshold: 150});
        });
    </script>
    <script src="{% static 'js/typeahead.bundle.min.js' %}" type="text/javascript"></script>
{% endblock js %}

<style>
    {% block style %}
        body{
            background: #24282f;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
    {% endblock style%}
</style>

{% block photo_adjustment %}
    <script type="text/javascript" src="{% static 'js/photo-auto-adjustment.min.js' %}"></script>
{% endblock photo_adjustment %}

{% block content %}
    {% if request.user != user %}
        <div class="col-md-2" style="margin-top: 43px;">
            <a href="{% url 'home' %}" class="submit-btn signin-btn" >my profile</a>
        </div>
    {% endif %}
    <!-- SEARCH -->
    <div class="search-container">
        <form role="search" action="/search/">
            <div class="custom-search-input">
                <div id="remote" class="input-group col-md-12 twitter-typeahead">
                    <input type="text" class="form-control input-lg typeahead tt-input" autocomplete="off" spellcheck="false" name="q" placeholder="Search" />
                    <span class="input-group-btn">
                        <button class="btn btn-lg" type="submit">
                            <span class="fa fa-search"></span>
                        </button>
                    </span>
                </div>
            </div>
        </form>
    </div>

    <!-- PROFILE INFO -->
    <div class="col-sm-12 account-home-profile">
        <div class="col-sm-12">
            <img class="company-home-profile-pic" src="{{ advertiser.default_company_logo }}" />
        </div>
        <div class="col-sm-6 col-sm-offset-3">
            <h2 class="account-home-profile-name">
                {{ advertiser.company_name }} <small>{{ user.username }}</small>
            </h2>
        </div>
        <div class="col-sm-8 col-sm-offset-2">
            <h5 class="account-home-profile-description">{{ advertiser.description }}</h5>
            <h5 class="account-home-profile-description">
                <a href="http://{{ advertiser.company_website }}">{{ advertiser.company_website }}</a>
            </h5>
            <h5 class="account-home-profile-description">
                <a href="{{ advertiser.hyperlink_twitter }}">@{{ advertiser.twitter }}</a>
            </h5>
            <h5 class="account-home-profile-description">
                <a href="{{ advertiser.hyperlink_instagram }}">@{{ advertiser.instagram }}</a>
            </h5>
        </div>
        <div class="col-sm-6 col-sm-offset-3">
            <div class="account-home-stats">
                <div class="account-home-stat">
                    <b>
                        {% if follow %}
                            {{ follow.get_following_count }}
                        {% else %}
                            0
                        {% endif %}
                    </b>
                </div>
                <div class="account-home-stat">
                    <b>
                        {% if follow %}
                            {{ follow.get_followers_count }}
                        {% else %}
                            0
                        {% endif %}
                    </b>
                </div>
                <div class="account-home-stat">
                    <b>
                        {{ photos.count }}
                    </b>
                </div>
            </div>

            <div class="account-home-stats" style="margin-top: -45px;">
                <div class="account-home-stat">
                    Supporting
                </div>
                <div class="account-home-stat">
                    Supporters
                </div>
                <div class="account-home-stat">
                    Creations
                </div>
            </div>

            {% if request.user == advertiser %}
                <a href="{% url 'accounts:account_settings' %}" class="submit-btn special-btn">Edit Profile</a>
            {% elif request.user == user %}
                <a href="{% url 'accounts:business_settings' %}" class="submit-btn special-btn">Edit Company</a>
            {% else %}
                <input id="follow_btn" 
                       class="submit-btn{% if request.user.username in follow.get_followers_usernames %} following-btn{% else %} go-btn{% endif %}" 
                       name="{{ user.id }}" 
                       value="{% if request.user.username in follow.get_followers_usernames %}Supporting{% else %}Support{% endif %}" 
                       type="button" />
            {% endif %}
        </div>
    </div>
    <!-- PICTURES -->
    <div class="ponder-items">
        {% for photo in photos %}
            <div class="ponder-item">
                {% if request.user == photo.creator %}
                    <button type="button" class="close">
                        <span aria-hidden="true">
                            <a href="{{ photo.get_delete_url }}" style="text-decoration: none;">&times;</a>
                        </span>
                    </button>
                {% endif %}
                <small>{{ photo.description }}</small>
                <img src="{{ photo.get_photo_url }}" class='lazy img-responsive'>
                <div class="photo-item-interactions">
                    <div class="photo-item-interaction">
                        <label class="like_count" style="cursor: default;">
                            {{ photo.like_count }} likes
                        </label>
                        <label style="cursor: default;">
                            {{ photo.comment_count }} comments
                        </label>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

<script>
    {% block jquery %}
        var usersDisplay = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('username'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            limit: 6,
            remote: {
                url: "{% url 'search_ajax' %}",
                replace: function(url, query) {
                    return url + "?q=" + query;
                }
            }
        });
        $('#remote .typeahead').typeahead({
            minLength: 1,
            highlight: true},
            {name: 'users-display',
            display: 'username',
            source: usersDisplay,
        });
        $('#follow_btn').click(function(e){
            e.preventDefault();
            var $follow_btn = $(this);
            if ($follow_btn.attr("class") == "submit-btn following-btn"){
                $follow_btn.val("Support");
                $follow_btn.removeClass("following-btn").addClass("go-btn");
            } else{
                $follow_btn.val("Supporting");
                $follow_btn.removeClass("go-btn").addClass("following-btn");
            }
            $.ajax({
                type: "POST",
                url: "{% url 'follow_ajax' %}",
                data: {
                    "user_id": $(this).attr("name"),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                },
                dataType: "json",
                success: function(data) {
                    if (data.viewer_has_followed) {
                        $('#followers_count').html(data.followers_count);
                    } else {
                        $('#followers_count').html(data.followers_count);
                    }
                },
                error: function (rs, e) {
                    alert('Sorry, there was an error with your request. Please try again later.');
                }
            });
        });
    {% endblock jquery %}
</script>

templates/advertisers/business_inquiry.html
{% extends 'simple_base.html' %}
{% load crispy_forms_tags %}

{% block title %} / Partnership Inquiry{% endblock %}

<style>
    {% block style %}
        body{
            background: #24282f; /* For browsers that do not support gradients */
            background: -webkit-linear-gradient(#3BC881, #4A9BE6); /* For Safari 5.1 to 6.0 */
            background: -o-linear-gradient(#3BC881, #4A9BE6); /* For Opera 11.1 to 12.0 */
            background: -moz-linear-gradient(#3BC881, #4A9BE6); /* For Firefox 3.6 to 15 */
            background: linear-gradient(#3BC881, #4A9BE6); /* Standard syntax */
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
    {% endblock style %}
</style>

{% block content %}
    <div class="col-sm-6 col-sm-offset-3 contact-container">
        <div>
            <h1>Partnership Inquiry</h1>
        </div>
        <h5>Thank you for your interest in OBY!</h5>
        <h5>We believe it is important to demonstrate acts of kindness to promote an inviting social environment. We do everything in our power to put others before ourselves, but help is always appreciated. This is where organizations like you play an important role.</h5>
        <h5>By partnering with OBY, we can make a difference... together! We are asking organizations to contribute promotional offers to the users. This includes, but not limited to: coupons, sample products, charitable fundraisers, etc.</h5>
        <h5>In return for your contribution, we can offer global brand awareness for your organization, customer feedback about your brand, analytics, and much more!</h5>
        <h5>We would love to further discuss this opportunity with you. Please fill out the form below, and we will be in touch shortly regarding the next steps.</h5>
        <h5>Thank you!</h5>
        <form method='POST' action='.'>
            {% csrf_token %}
            {{ form|crispy }}
            <input type='submit' value='Submit' class='submit-btn special-btn' />
        </form>
    </div>
    <div class="col-sm-12 visitor-footer">
        <a href="{% url 'home' %}" class="visitor-footer-item">Home</a>
        <a href="{% url 'about' %}" class="visitor-footer-item">About</a>
        <a href="mailto:team@obystudio.com" class="visitor-footer-item">team@obystudio.com</a>
        <a href="{% url 'privacy_policy' %}" class="visitor-footer-item">Privacy</a>
        <a href="{% url 'terms_of_use' %}" class="visitor-footer-item">Terms</a>
        <p class="visitor-footer-item">&copy; 2016 OBY</p>
    </div>
{% endblock content %}

templates/advertisers/business_inquiry_email.html
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>OBY Partnership Inquiry</title>
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0;
}
img {
  max-width: 600px;
  width: 100%;
}
body {
  -webkit-font-smoothing: antialiased;
  height: 100%;
  -webkit-text-size-adjust: none;
  width: 100% !important;
}
/* -------------------------------------
    ELEMENTS
------------------------------------- */
a {
  color: #348eda;
}
.btn-primary {
  Margin-bottom: 10px;
  width: auto !important;
}
.btn-primary td {
  background-color: #348eda; 
  border-radius: 25px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
  font-size: 14px; 
  text-align: center;
  vertical-align: top; 
}
.btn-primary td a {
  background-color: #348eda;
  border: solid 1px #348eda;
  border-radius: 25px;
  border-width: 10px 20px;
  display: inline-block;
  color: #ffffff;
  cursor: pointer;
  font-weight: bold;
  line-height: 2;
  text-decoration: none;
}
.last {
  margin-bottom: 0;
}
.first {
  margin-top: 0;
}
.padding {
  padding: 10px 0;
}
/* -------------------------------------
    BODY
------------------------------------- */
table.body-wrap {
  padding: 20px;
  width: 100%;
}
table.body-wrap .container {
  border: 1px solid #f0f0f0;
}
/* -------------------------------------
    FOOTER
------------------------------------- */
table.footer-wrap {
  clear: both !important;
  width: 100%;  
}
.footer-wrap .container p {
  color: #666666;
  font-size: 12px;
  
}
table.footer-wrap a {
  color: #999999;
}
/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1, 
h2, 
h3 {
  color: #111111;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: 200;
  line-height: 1.2em;
  margin: 40px 0 10px;
}
h1 {
  font-size: 36px;
}
h2 {
  font-size: 28px;
}
h3 {
  font-size: 22px;
}
p, 
ul, 
ol {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 10px;
}
ul li, 
ol li {
  margin-left: 5px;
  list-style-position: inside;
}
/* ---------------------------------------------------
    RESPONSIVENESS
------------------------------------------------------ */
/* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
.container {
  clear: both !important;
  display: block !important;
  Margin: 0 auto !important;
  max-width: 600px !important;
}
/* Set the padding on the td rather than the div for Outlook compatibility */
.body-wrap .container {
  padding: 20px;
}
/* This should also be a block element, so that it will fill 100% of the .container */
.content {
  display: block;
  margin: 0 auto;
  max-width: 600px;
}
/* Let's make sure tables in the content area are 100% wide */
.content table {
  width: 100%;
}
</style>
</head>

<body bgcolor="#f6f6f6">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td>
            <p>Hi!</p>
            <p>Thank you for your interest in partnering with OBY.<br/>
            We are an optimisitc bunch, so in the meantime, could you please apply for a company profile by clicking the link below? </p>
            <h2>Register company:</h2>
            <!-- button -->
            <table class="btn-primary" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td>
                  <a href="http://{{ domain }}{% url 'contact:business_signup' %}">COMPANY REGISTRATION</a>
                </td>
              </tr>
            </table>
            <!-- /button -->
            <br/>
            <br/>
            <p>If you don't think this request was made by you, please ignore this email.</p>
            <p>Thanks for using OBY!</p>
            <p><a href="http://{{ domain }}">www.obystudio.com</a></p>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->
    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->

<!-- footer -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">
      
      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <!-- <p>Don't like these annoying emails? <a href="#"><unsubscribe>Unsubscribe</unsubscribe></a>.</p> -->
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->
      
    </td>
    <td></td>
  </tr>
</table>
<!-- /footer -->

</body>
</html>

templates/advertisers/business_settings.html
{% extends "simple_base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ username }} / Company Settings{% endblock title %}

<style>
    {% block style %}
        body{
            background: #24282f;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
    {% endblock style%}
</style>

{% block content %}
    <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
            <li><a href="{% url 'profile_view' request.user.username %}">back to profile</a>
            <br/><br/>
            <li class="active"><a href="{% url 'accounts:business_settings' %}">company settings<span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'accounts:account_settings' %}">profile</a></li>
            <li><a href="{% url 'accounts:password_change' %}">change password</a></li>
            <li>
                <a href="mailto:team@obystudio.com?subject=Contact us&body=Have a question, concern, comment, or just want someone to talk to? Please feel free to reach out! We'd be more than happy to help. Thank you for using OBY!">contact us</a>
            </li>
            <li><a href="{% url 'accounts:logout' %}">sign out</a></li>
        </ul>
    </div>
    <div class="col-sm-7 col-sm-offset-3 account-settings-container general-container">
        <h2 class="page-header settings-title">Company Settings</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ company_change_form|crispy }}
            <input class="submit-btn go-btn-form" type="submit" value="Update Settings" />
        </form>    
    </div>
{% endblock content %}

templates/advertisers/business_signup.html
{% extends "simple_base.html" %}
{% load crispy_forms_tags %}

{% block title %}OBY / Company Application{% endblock title %}

<style>
    {% block style %}
        body{
            background: #F9615B; /* For browsers that do not support gradients */
            background: -webkit-linear-gradient(#87080c, #b44d3e); /* For Safari 5.1 to 6.0 */
            background: -o-linear-gradient(#87080c, #b44d3e); /* For Opera 11.1 to 12.0 */
            background: -moz-linear-gradient(#87080c, #b44d3e); /* For Firefox 3.6 to 15 */
            background: linear-gradient(#87080c, #b44d3e); /* Standard syntax */
        }
    {% endblock style %}
</style>

{% block content %}
    <div class="authentication-container">
        <div class="col-sm-12">
            <h1>Register</h1>
            <br/>
        </div>
        <div class="col-sm-4 col-sm-offset-4">
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}
                {{ form|crispy }}
                <br/>
                <input type="hidden" name="next" value="{% url 'accounts:business_settings' %}" />
                <input class="submit-btn signin-btn btn-block" type="submit" value="Create Company Account" />
            </form>
            {% if title == "Register" %}
                <p class="account-create-agreement">
                    Creating an account means you're okay with OBY's<br/>
                    <a href="{% url 'terms_of_use' %}">Terms</a> and <a href="{% url 'privacy_policy' %}">Privacy</a> policies.
                </p>
                {% endif %}
            <br/>
            <div class="redirect-link">
                <br/>
                <p>Already have an account? <a href="mailto:partnerships@obystudio.com?subject=Company Signup Existing Account&body=Please tell us which username you would like to use for your company. Please make sure you already own the account, or have legal rights to the name. Thank you!">Email us. We'll transfer the account to a company profile.</a></p>
            </div>
        </div>
        <div class="col-sm-12 visitor-footer" style="text-shadow: none;">
            <a href="{% url 'home' %}" class="visitor-footer-item">OBY</a>
            <a href="{% url 'about' %}" class="visitor-footer-item">About</a>
            <a href="mailto:team@obystudio.com" class="visitor-footer-item">team@obystudio.com</a>
            <a href="{% url 'privacy_policy' %}" class="visitor-footer-item">Privacy</a>
            <a href="{% url 'terms_of_use' %}" class="visitor-footer-item">Terms</a>
            <p class="visitor-footer-item">&copy; 2016 OBY</p>
        </div>
    </div>
{% endblock content %}