accounts/urls.py
from django.conf.urls import url

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^account/$', views.account_settings, name='account_settings'),
    url(r'^business/settings/$', views.business_settings,
        name='business_settings'),
    url(r'^signout/$', views.auth_logout, name='logout'),
    url(r'^password/change/$', views.password_change, name="password_change"),
    url(r'^password/reset/$', views.password_reset, name="password_reset"),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name="password_reset_confirm"),
]

api/urls.py
from django.conf.urls import url

from push_notifications.api.views import APNSDeviceAuthorizedViewSet

from . import views
from .views import APIHomeView, TimelineAPIView
from .views import (AccountCreateAPIView,
                    MyUserDetailAPIView, MyUserListAPIView)
from .views import CommentCreateAPIView, CommentDetailAPIView
from .views import HashtagPhotoListAPIView, HashtagTrendingListAPIView
from .views import (CategoryDetailAPIView, CategoryListAPIView,
                    PhotoListAPIView, PhotoCreateAPIView, PhotoDetailAPIView)
from .views import NotificationAPIView, NotificationAjaxAPIView
from .views import (PasswordChangeView, PasswordResetView,
                    PasswordResetConfirmView)
from .views import (ProductCreateAPIView, ProductDetailAPIView,
                    ProductListAPIView, ProductRedeemedListAPIView)
from .views import SearchListAPIView


urlpatterns = [
    # G E N E R A L
    url(r'^$', APIHomeView.as_view(),
        name='api_home'),
    url(r'^homepage/$', views.homepage_api_view,
        name='homepage_api'),
    url(r'^timeline/$', TimelineAPIView.as_view(),
        name='timeline_api'),
    url(r'^search/$', SearchListAPIView.as_view(),
        name='search_api'),
    url(r'^device/apns/$',
        APNSDeviceAuthorizedViewSet.as_view({'post': 'create'}),
        name='create_apns_device'),

    # A C C O U N T S
    url(r'^accounts/$', MyUserListAPIView.as_view(),
        name='user_account_list_api'),
    url(r'^accounts/create/$', AccountCreateAPIView.as_view(),
        name='account_create_api'),
    url(r'^accounts/(?P<username>[\w.@+-]+)/$', MyUserDetailAPIView.as_view(),
        name='user_account_detail_api'),
    url(r'^support/(?P<user_pk>\d+)/$', views.follow_create_api,
        name='follow_create_api'),
    url(r'^block/(?P<user_pk>\d+)/$', views.block_user_api,
        name='block_user_api'),

    # A U T H E N T I C A T I O N
    url(r'^password/reset/$', PasswordResetView.as_view(),
        name='rest_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(),
        name='rest_password_reset_confirm'),
    url(r'^password/change/$', PasswordChangeView.as_view(),
        name='rest_password_change'),

    # C O M M E N T S
    url(r'^comments/create/$', CommentCreateAPIView.as_view(),
        name='comment_create_api'),
    url(r'^comments/(?P<id>\d+)/$', CommentDetailAPIView.as_view(),
        name='comment_detail_api'),

    # F L A G S
    url(r'^flag/create/(?P<photo_pk>\d+)/$', views.flag_create_api,
        name='flag_create_api'),

    # H A S H T A G S
    url(r'^hashtags/$', HashtagPhotoListAPIView.as_view(),
        name='hashtag_photo_list_api'),
    url(r'^hashtags/trending/$', HashtagTrendingListAPIView.as_view(),
        name='hashtag_trending_list_api'),

    # N O T I F I C A T I O N S
    url(r'^notifications/$', NotificationAPIView.as_view(),
        name='notification_list_api'),
    url(r'^notifications/unread/$', NotificationAjaxAPIView.as_view(),
        name='get_unread_notifications_api'),

    # P H O T O S
    url(r'^categories/$', CategoryListAPIView.as_view(),
        name='category_list_api'),
    url(r'^categories/(?P<slug>[\w-]+)/$', CategoryDetailAPIView.as_view(),
        name='category_detail_api'),
    url(r'^photos/$', PhotoListAPIView.as_view(),
        name='photo_list_api'),
    url(r'^photos/create/$', PhotoCreateAPIView.as_view({'post': 'create'}),
        name='photo_create_api'),
    url(r'^photos/(?P<cat_slug>[\w-]+)/(?P<photo_slug>[\w-]+)/$',
        PhotoDetailAPIView.as_view(),
        name='photo_detail_api'),
    url(r'^like/(?P<photo_pk>\d+)/$', views.like_create_api,
        name='like_create_api'),

    # S H O P
    url(r'^shop/$', ProductListAPIView.as_view(),
        name='product_list_api'),
    url(r'^shop/redeemed/$', ProductRedeemedListAPIView.as_view(),
        name='product_redeemed_api'),
    url(r'^shop/create/$', ProductCreateAPIView.as_view({'post': 'create'}),
        name='product_create_api'),
    url(r'^shop/product/(?P<product_slug>[\w-]+)/$',
        ProductDetailAPIView.as_view(),
        name='product_detail_api'),
    url(r'^shop/rewards/check/$', views.reward_check_view,
        name='reward_check_view'),
    url(r'^shop/rewards/redeemed/$', views.reward_redeemed_view,
        name='reward_redeemed_view'),
    url(r'^shop/rewards/purchase/(?P<product_pk>\d+)/$',
        views.reward_purchase_view,
        name='reward_purchase_view'),
]

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.db.models import F
from django.http import Http404, JsonResponse
from django.shortcuts import (get_object_or_404, HttpResponseRedirect,
                              redirect, render)
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import cache_page, never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.http import require_http_methods

from notifications.signals import notify
from photos.models import Photo
from .forms import (AccountBasicsChangeForm, CompanyBasicsChangeForm,
                    LoginForm, PasswordChangeForm, RegisterForm,
                    PasswordResetForm, SetPasswordForm)
from .models import Advertiser, Follower, MyUser

# Create your views here.


@login_required
@cache_page(60 * 5)
def profile_view(request, username):
    # page_view.send(
    #     user,
    #     page_path=request.get_full_path(),
    # )
    user = get_object_or_404(MyUser, username=username)

    if user.username == "anonymous":
        return render(request, "accounts/anonymous.html", {})
    elif request.user in user.blocking.all():
        raise PermissionDenied
    elif not user.is_active:
        raise Http404
    else:
        try:
            advertiser = Advertiser.objects.get(user__username=username)
        except Advertiser.DoesNotExist:
            advertiser = None

        try:
            follow = (Follower.objects.select_related('user')
                                      .prefetch_related(
                                          'following', 'followers')
                                      .get(user=user))
        except Follower.DoesNotExist:
            follow = None

        photos = (Photo.objects.filter(creator=user)
                               .select_related('category', 'creator')
                               .prefetch_related('likers')[:150])

        template = "accounts/profile_view.html"
        context = {
            'follow': follow,
            'photos': photos,
            'user': user
        }
        if advertiser:
            template = "advertisers/advertiser_view.html"
            context.update({'advertiser': advertiser})
        return render(request, template, context)


@cache_page(60 * 4)
def followers_thread(request, username):
    try:
        user = MyUser.objects.get(username=username)
    except MyUser.DoesNotExist:
        raise Http404
    followers_set = (Follower.objects.filter(user=user.id)
                                     .select_related('user')
                                     .prefetch_related('followers'))
    return render(request, "accounts/followers_thread.html",
                  {'followers_set': followers_set})


@cache_page(60 * 4)
def following_thread(request, username):
    try:
        user = MyUser.objects.get(username=username)
    except MyUser.DoesNotExist:
        raise Http404
    following_set = (Follower.objects.filter(user=user.id)
                                     .select_related('user')
                                     .prefetch_related('following'))
    return render(request, "accounts/following_thread.html",
                  {"following_set": following_set})


@login_required
@require_http_methods(['POST'])
def follow_ajax(request):
    viewing_user = request.user
    user_id = request.POST.get('user_id')
    user = get_object_or_404(MyUser, id=user_id)
    follower, created = Follower.objects.get_or_create(user=viewing_user)
    followed, created = Follower.objects.get_or_create(user=user)

    try:
        user_followed = (Follower.objects.select_related('user')
                                         .get(user=user, followers=follower))
    except Follower.DoesNotExist:
        user_followed = None

    if user_followed:
        followed.followers.remove(follower)
        viewer_has_followed = False
        viewing_user.available_points = F('available_points') - 1
        viewing_user.total_points = F('total_points') - 1
    else:
        followed.followers.add(follower)
        viewer_has_followed = True
        viewing_user.available_points = F('available_points') + 1
        viewing_user.total_points = F('total_points') + 1

        notify.send(
            viewing_user,
            recipient=user,
            verb='is now supporting you'
        )
        if user in viewing_user.blocking.all():
            viewing_user.blocking.remove(user)

    followed.save()
    viewing_user.save()

    data = {
        "viewer_has_followed": viewer_has_followed,
        "followers_count": followed.get_followers_count()
    }
    return JsonResponse(data)


@login_required
def account_settings(request):
    user = request.user

    try:
        advertiser = Advertiser.objects.get(user=request.user)
    except Advertiser.DoesNotExist:
        advertiser = None

    account_change_form = AccountBasicsChangeForm(request.POST or None,
                                                  request.FILES or None,
                                                  instance=user, user=user)
    if request.method == 'POST':
        if account_change_form.is_valid():
            email = account_change_form.cleaned_data['email']
            edu_email = account_change_form.cleaned_data['edu_email']

            account_change_form.email = email
            account_change_form.edu_email = edu_email
            account_change_form.save()
            messages.success(request,
                             "You have successfully updated your profile.")

    context = {
        'account_change_form': account_change_form,
        'advertiser': advertiser
    }
    return render(request, 'accounts/settings/account_settings.html', context)


@login_required
def business_settings(request):
    try:
        user = Advertiser.objects.get(user=request.user)
    except Advertiser.DoesNotExist:
        user = None

    if user:
        company_change_form = CompanyBasicsChangeForm(request.POST or None,
                                                      request.FILES or None,
                                                      instance=user, user=user)
        if request.method == 'POST':
            if company_change_form.is_valid():
                company_name = company_change_form.cleaned_data['company_name']

                company_change_form.company_name = company_name
                company_change_form.save()
                messages.success(request,
                                 "You have successfully updated your profile.")
        context = {
            'company_change_form': company_change_form,
            'username': user.user.username
        }
        return render(request, 'advertisers/business_settings.html', context)
    return HttpResponseRedirect(reverse("accounts:account_settings"))


# @login_required
# @cache_page(60 * 3)
# def product_purchase_history(request):
#     user = request.user
#     history = Product.objects.filter(buyers=user)
#     return render(request, "accounts/settings/product_purchase_history.html",
#                   {"queryset": history})


# @login_required
# @cache_page(60 * 3)
# def advertiser_analytics(request):
#     user = request.user

#     if user.is_advertiser:
#         history = Product.objects.filter(owner=user)
#         total_creations = history.aggregate(Sum("owner")).get(
#             "owner__sum", 0)
#         total_downloads = history.aggregate(Sum("buyers")).get(
#             "buyers__sum", 0)

#         context = {
#             "total_creations": total_creations,
#             "total_downloads": total_downloads,
#             "queryset": history,
#             "user": user
#         }
#         return render(request, "accounts/settings/advertiser_analytics.html",
#                       context)
#     else:
#         return HttpResponseRedirect(reverse("home"))


@sensitive_post_parameters()
@login_required
def password_change(request):
    try:
        advertiser = Advertiser.objects.get(user=request.user)
    except Advertiser.DoesNotExist:
        advertiser = None

    form = PasswordChangeForm(request.POST or None, user=request.user)

    if request.method == "POST":
        if form.is_valid():
            password = form.cleaned_data['password2']
            current_user = form.user
            current_user.set_password(password)
            current_user.save()
            update_session_auth_hash(request, form.user)
            messages.success(request,
                             "You have successfully changed your password.")
    context = {
        'advertiser': advertiser,
        'form': form
    }
    return render(request, 'accounts/settings/password_change.html', context)


def password_reset(request, from_email=settings.EMAIL_FROM,
                   template_name='accounts/settings/password_reset_form.html',
                   email_template_name='accounts/settings/password_reset_email.html',
                   subject_template_name='OBY Reset Account Password',
                   password_reset_form=PasswordResetForm,
                   token_generator=default_token_generator,
                   html_email_template_name='accounts/settings/password_reset_email.html'):
    if request.user.is_authenticated():
        return redirect('home')
    else:
        if request.method == "POST":
            form = password_reset_form(request.POST)
            if form.is_valid():
                opts = {
                    'use_https': request.is_secure(),
                    'token_generator': token_generator,

templates/accounts/settings/account_settings.html
{% extends "simple_base.html" %}
{% load crispy_forms_tags %}

{% block title %}OBY / Profile Settings{% endblock title %}

<style>
    {% block style %}
        body{
            background: #24282f;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
    {% endblock style%}
</style>

{% block content %}
    <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
            <li><a href="{% url 'profile_view' request.user.username %}">back to profile</a>
            <br/><br/>
            {% if advertiser %}
                <li><a href="{% url 'accounts:business_settings' %}">company settings</a></li>
            {% endif %}
            <li class="active"><a href="{% url 'accounts:account_settings' %}">profile<span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'accounts:password_change' %}">change password</a></li>
            <li>
                <a href="mailto:team@obystudio.com?subject=Contact us&body=Have a question, concern, comment, or just want someone to talk to? Please feel free to reach out! We'd be more than happy to help. Thank you for using OBY!">contact us</a>
            </li>
            <li><a href="{% url 'accounts:logout' %}">sign out</a></li>
        </ul>
    </div>
    <div class="col-sm-7 col-sm-offset-3 account-settings-container general-container">
        <h2 class="page-header settings-title">Profile Settings</h2>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ account_change_form|crispy }}
            <input class="submit-btn go-btn-form" type="submit" value="Update Settings" />
        </form>    
    </div>
{% endblock content %}

templates/accounts/settings/password_change.html
{% extends "simple_base.html" %}
{% load crispy_forms_tags %}

{% block title %}OBY / Change Password{% endblock title %}

<style>
    {% block style %}
        body{
            background: #24282f;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        }
    {% endblock style%}
</style>

{% block content %}
    <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
            <li><a href="{% url 'profile_view' request.user.username %}">back to profile</a>
            <br/><br/>
            {% if advertiser %}
                <li><a href="{% url 'accounts:business_settings' %}">company settings</a></li>
            {% endif %}
            <li><a href="{% url 'accounts:account_settings' %}">profile</a></li>
            <li class="active">
                <a href="{% url 'accounts:password_change' %}">
                    change password <span class="sr-only">(current)</span>
                </a>
            </li>
            <li>
                <a href="mailto:team@obystudio.com?subject=Contact us&body=Have a question, concern, comment, or just want someone to talk to? Please feel free to reach out! We'd be more than happy to help. Thank you for using OBY!">contact us</a>
            </li>
            <li><a href="{% url 'accounts:logout' %}">sign out</a></li>
        </ul>
    </div>
    <div class="col-sm-7 col-sm-offset-3 account-settings-container general-container">
        <h2 class="page-header settings-title">Change Password</h2>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="submit-btn go-btn-form" type="submit" value="Update Password" />
        </form>    
    </div>
{% endblock content %}

templates/accounts/settings/password_reset_email.html
<!-- {% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because your email address was entered in the forgotten password form at OBY.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using OBY!" %}

{% trans "If you believe you have received this email in error, please ignore it." %}

{% blocktrans %}The OBY team{% endblocktrans %}

{% endautoescape %} -->
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>OBY Reset Account Password</title>
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0;
}
img {
  max-width: 600px;
  width: 100%;
}
body {
  -webkit-font-smoothing: antialiased;
  height: 100%;
  -webkit-text-size-adjust: none;
  width: 100% !important;
}
/* -------------------------------------
    ELEMENTS
------------------------------------- */
a {
  color: #348eda;
}
.btn-primary {
  Margin-bottom: 10px;
  width: auto !important;
}
.btn-primary td {
  background-color: #348eda; 
  border-radius: 25px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
  font-size: 14px; 
  text-align: center;
  vertical-align: top; 
}
.btn-primary td a {
  background-color: #348eda;
  border: solid 1px #348eda;
  border-radius: 25px;
  border-width: 10px 20px;
  display: inline-block;
  color: #ffffff;
  cursor: pointer;
  font-weight: bold;
  line-height: 2;
  text-decoration: none;
}
.last {
  margin-bottom: 0;
}
.first {
  margin-top: 0;
}
.padding {
  padding: 10px 0;
}
/* -------------------------------------
    BODY
------------------------------------- */
table.body-wrap {
  padding: 20px;
  width: 100%;
}
table.body-wrap .container {
  border: 1px solid #f0f0f0;
}
/* -------------------------------------
    FOOTER
------------------------------------- */
table.footer-wrap {
  clear: both !important;
  width: 100%;  
}
.footer-wrap .container p {
  color: #666666;
  font-size: 12px;
  
}
table.footer-wrap a {
  color: #999999;
}
/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1, 
h2, 
h3 {
  color: #111111;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: 200;
  line-height: 1.2em;
  margin: 40px 0 10px;
}
h1 {
  font-size: 36px;
}
h2 {
  font-size: 28px;
}
h3 {
  font-size: 22px;
}
p, 
ul, 
ol {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 10px;
}
ul li, 
ol li {
  margin-left: 5px;
  list-style-position: inside;
}
/* ---------------------------------------------------
    RESPONSIVENESS
------------------------------------------------------ */
/* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
.container {
  clear: both !important;
  display: block !important;
  Margin: 0 auto !important;
  max-width: 600px !important;
}
/* Set the padding on the td rather than the div for Outlook compatibility */
.body-wrap .container {
  padding: 20px;
}
/* This should also be a block element, so that it will fill 100% of the .container */
.content {
  display: block;
  margin: 0 auto;
  max-width: 600px;
}
/* Let's make sure tables in the content area are 100% wide */
.content table {
  width: 100%;
}
</style>
</head>

<body bgcolor="#f6f6f6">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">

      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td>
            <p>Hey,</p>
            <p>We wanted to let you know that your email was entered in the forgotten password form at OBY.<br/>
            If you made this request, please click the button below to create a new password:</p>
            <h2>Password reset:</h2>
            <!-- button -->
            <table class="btn-primary" cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td>
                  <a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">RESET PASSWORD</a>
                </td>
              </tr>
            </table>
            <!-- /button -->
            <br/>
            <br/>
            <p>If you forgot, your username is: <b>{{ user.get_username|upper }}</b></p>
            <p>If you don't think this was you, please ignore this email.</p>
            <p>Thanks for using OBY!</p>
            <p><a href="https://www.obystudio.com/">www.obystudio.com</a></p>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->
    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->

<!-- footer -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">
      
      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <!-- <p>Don't like these annoying emails? <a href="#"><unsubscribe>Unsubscribe</unsubscribe></a>.</p> -->
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->
      
    </td>
    <td></td>
  </tr>
</table>
<!-- /footer -->

</body>
</html>

templates/accounts/settings/password_reset_form.html
{% extends "simple_base.html" %}
{% load crispy_forms_tags %}

{% block title %}OBY / Reset Password{% endblock title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3 contact-container">
        <h1>Reset Password</h1>
        <h5>Please enter the email address of your account below.</h5>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="submit-btn signin-btn" type="submit" value="Send" />
        </form>    
    </div>
    <div class="col-sm-12 visitor-footer">
        <a href="{% url 'home' %}" class="visitor-footer-item">Home</a>
        <a href="{% url 'about' %}" class="visitor-footer-item">About</a>
        <a href="mailto:team@obystudio.com" class="visitor-footer-item">team@obystudio.com</a>
        <a href="{% url 'privacy_policy' %}" class="visitor-footer-item">Privacy</a>
        <a href="{% url 'terms_of_use' %}" class="visitor-footer-item">Terms</a>
        <a href="{% url 'login' %}" class="visitor-footer-item">Sign in</a>
        <p class="visitor-footer-item">&copy; 2016 OBY</p>
    </div>
{% endblock content %}

templates/accounts/settings/password_set.html
{% extends "simple_base.html" %}
{% load crispy_forms_tags %}

{% block title %}OBY / Set Password{% endblock title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3 contact-container">
        <h1>Create New Password</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="submit-btn signin-btn" type="submit" value="Create Password" />
        </form>    
    </div>
    <div class="col-sm-12 visitor-footer">
        <a href="{% url 'home' %}" class="visitor-footer-item">Home</a>
        <a href="{% url 'about' %}" class="visitor-footer-item">About</a>
        <a href="mailto:team@obystudio.com" class="visitor-footer-item">team@obystudio.com</a>
        <a href="{% url 'privacy_policy' %}" class="visitor-footer-item">Privacy</a>
        <a href="{% url 'terms_of_use' %}" class="visitor-footer-item">Terms</a>
        <a href="{% url 'login' %}" class="visitor-footer-item">Sign in</a>
        <p class="visitor-footer-item">&copy; 2016 OBY</p>
    </div>
{% endblock content %}